version: '3.8'

services:
  user-service:
    image: esgi/user-service
    build: ./user-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-$(cat /run/secrets/postgres_user)}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-$(cat /run/secrets/postgres_password)}
      POSTGRES_DB: user_db
    secrets:
      - postgres_user
      - postgres_password
    restart: always
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/users"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      placement:
        constraints:
          - 'node.role==worker'
    networks:
      - esgi

  task-service:
    image: esgi/task-service
    build: ./task-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      placement:
        constraints:
          - 'node.role==worker'
    networks:
      - esgi

  web-frontend:
    image: esgi/web-frontend
    build: ./web-frontend
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - user-service
      - task-service
    deploy:
      mode: global
      update_config:
        parallelism: 2
    networks:
      - esgi

  postgres:
    image: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: user_db
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
    networks:
      - esgi

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password

volumes:
  postgres-data:

networks:
  esgi:
    driver: overlay
